# Generated by Django 5.2.8 on 2025-12-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_m_address_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_sex',
            field=models.CharField(choices=[('male', '남자'), ('female', '여자')], verbose_name='성'),
        ),
    ]
